--- #YAML:1.0
name:               Catalyst-TraitFor-Component-ConfigPerSite
version:            0.02
abstract:           ~
author:
    - Aaron Trevena <teejay@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cache::Cache:         0
    Catalyst:             0
    Moose:                0
    Test::HTML::Form:     0
    Test::Pod:            0
    Test::Pod::Coverage:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
